# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0aced73a44132d6cf0e2e75f99b0ae99ee055dba9a64a93db860bfc26c3064e93cef8b7104c7ca5e46cfd8e8293bea2c886312dba839e2b11fcaef27c04441d9

test:
  secret_key_base: b3bc81e98270907fd9378146f707089af0d47084fffa1d2267fdd51b33fc63c5c1bb77728a46755999254fa74f7730939ffa37ae08b0e6b5d02edf6cf8a68c66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
